CREATE TABLE [dbo].[Organizations]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Title] NVARCHAR(100) NOT NULL,
	[ResponsibilityType] INT NOT NULL,
	[Description] NVARCHAR(255) NULL
)
