CREATE TABLE [dbo].[States]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Title] NVARCHAR(100) NOT NULL UNIQUE,
	[Language] NVARCHAR(100) NOT NULL,
	[LanguageCode] NVARCHAR(10) NOT NULL UNIQUE,
)
